### ISSUE TITLE
401

### ISSUE THREAD

**Issue by usrlocalangelo** [camelotls/actions-jira-integration#378]
UserName and Password are both right. 
```
{"name":"actions-jira-integration","hostname":"866a1edb5608","pid":1,"level":40,"msg":"POST request createSession encountered the following error: Response code 401 (Unauthorized)","time":"2023-07-01T02:18:22.736Z","v":0}
{"name":"actions-jira-integration","hostname":"866a1edb5608","pid":1,"level":40,"msg":"Login failed","time":"2023-07-01T02:18:22.736Z","v":0}
{"name":"actions-jira-integration","hostname":"866a1edb5608","pid":1,"level":40,"msg":"","time":"2023-07-01T02:18:22.736Z","v":0}
(node:1) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Jira session cannot be created: Response code 401 (Unauthorized)
    at Object.createSession (/helpers/jira-helpers.js:29:3)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async kickOffAction (/index.js:61:23)
    at async /index.js:163:3
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by gromanas** [comment]
No further investigation as no info has been provided
